const showNextVideo = () => {
  document
    .getElementsByClassName("secondery-video")[0]
    .classList.add("move-sec-video-left");
  document
    .getElementsByClassName("secondery-video")[0]
    .classList.remove("move-sec-video-right");
  document
    .getElementsByClassName("main-video")[0]
    .classList.add("move-main-video-right");
  document
    .getElementsByClassName("main-video")[0]
    .classList.remove("move-main-video-left");
  document
    .getElementsByClassName("triggers")[0]
    .children[0].classList.add("main");
  document
    .getElementsByClassName("triggers")[0]
    .children[1].classList.remove("main");
};

const showPrevVideo = () => {
  document
    .getElementsByClassName("secondery-video")[0]
    .classList.add("move-sec-video-right");
  document
    .getElementsByClassName("secondery-video")[0]
    .classList.remove("move-sec-video-left");
  document
    .getElementsByClassName("main-video")[0]
    .classList.add("move-main-video-left");
  document
    .getElementsByClassName("main-video")[0]
    .classList.remove("move-main-video-right");
  document
    .getElementsByClassName("triggers")[0]
    .children[1].classList.add("main");
  document
    .getElementsByClassName("triggers")[0]
    .children[0].classList.remove("main");
};
